apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-service-deployment
  template:
    metadata:
      labels:
        app: forex-service-deployment
    spec:
      containers:
      - name: forex-service
        image: forex-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: forex-service
spec:
  type: NodePort
  selector:
    app: forex-service-deployment
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000